spring.application.name=discovery-server

#Puerto estandar de Eureka
server.port=8761

#Configuracion de Eureka
eureka.client.register-with-eureka=false
eureka.client.register-with-eureka.fetch-registry=false